### ISSUE TITLE
How to manage another name for 'status' attribute?

### ISSUE THREAD

**Issue by ilbassa** [raoul2000/yii2-wizflow#6]
Hi, I have this error:
`Setting unknown property: common\models\Domande::status`
I think because I don't use `status` attribute to keep the status value but I have an attribute called `STATO`.

How I can change the default status attribute?

**Comment by ilbassa** [comment]
I had to change:
```
$statusAttribute = 'STATO';
if( isset($attributes[$statusAttribute]) == false ) {
   throw new Exception('missing attribute "status"');
}
$status = $this->workflowSource->getStatus($attributes[$statusAttribute]);
```
in line 122:127 of WizflowManager

and

```
$config['STATO'] =  $status->getId();
```
on line 267 of WizflowManager

is there the possibility of parametrize $statusAttribute?

**Comment by raoul2000** [comment]
Hi,
please note that this repo is for a *proof fo concept* and so, I don't plan to modify it (except of course to fix bug).
Thahs being said, it is possible to choose the attribute name you want to use store the status. This is done when initializinng the *SimpleWorkblowBehavior*. Check [this example](http://raoul2000.github.io/yii2-workflow/special-cookbook/). The `statusAttribute` is used to define the name of the column that is used to store the status value.
Hope it helps

😎
